dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules

before_script:
  - echo $PROXY_CONF | base64 -d > ./proxy-conf.js

script:
  - npm run webdriver-update-ci
  - xvfb-run yarn test:ci
  - xvfb-run -a yarn e2e:ci
