dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules

install:
  - yarn install

before_script:
  - scripts/ci/add-proxy-conf.sh

script:
  - xvfb-run -a yarn e2e
