dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

services:
  - docker

addons:
  chrome: stable
  apt:
    packages:
      - docker-ce

cache:
  yarn: true
  directories:
  - node_modules

env:
  global:
    - DOCKER_USER=bwsw
    - DOCKER_REPO=cloudstack-ui

before_install:
  - google-chrome-stable --headless --no-sandbox

install:
  - yarn install

before_script:
  - ./scripts/ci/add-proxy-conf.sh
  - ./scripts/ci/install-simulator.sh

script:
  - xvfb-run -a yarn e2e
  - yarn lint
  - xvfb-run -a yarn test --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage

after_success:
  - yarn coveralls
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    curl $JENKINS_DEPLOY_URL
    fi

before_deploy:
  - docker build -t ${DOCKER_USER}/${DOCKER_REPO} .

deploy:
  - provider: script
    script: ./scripts/ci/publish-docker-image.sh
    on:
      all_branches: true
