dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

services:
  - docker

addons:
  chrome: stable
  apt:
    packages:
      - docker-ce

cache:
  yarn: true
  directories:
  - node_modules

env:
  global:
    - DOCKER_USER=bwsw
    - DOCKER_REPO=cloudstack-ui

install:
  - yarn install

before_script:
  - ./scripts/ci/install-simulator.sh
  - ./scripts/ci/add-proxy-conf.sh
  - curl -v -X POST "http://127.0.0.1:4222/client/api?command=login&username=admin&password=password&domain=%2F&response=json"
  - curl -v -X POST "https://cs2-1.netpoint-dc.com/client/api?command=login&username=admin&password=password&domain=%2F&response=json"

script:
  - curl -v -X POST "http://127.0.0.1:4222/client/api?command=login&username=admin&password=password&domain=%2F&response=json"
  - curl -v -X POST "https://cs2-1.netpoint-dc.com/client/api?command=login&username=admin&password=password&domain=%2F&response=json"
  - yarn e2e

after_success:
  - yarn coveralls
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    curl $JENKINS_DEPLOY_URL
    fi

before_deploy:
  - docker build -t ${DOCKER_USER}/${DOCKER_REPO} .

deploy:
  - provider: script
    script: ./scripts/ci/publish-docker-image.sh
    on:
      all_branches: true
