dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

services:
  - docker

addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - google-chrome-stable --headless --no-sandbox

install:
  - yarn install

before_script:
  - ./scripts/ci/add-proxy-conf.sh
  - ./scripts/ci/install-simulator.sh

script:
  - yarn lint
  - xvfb-run yarn test:ci
  - xvfb-run yarn e2e:ci

after_success:
  - yarn coveralls
  - ./scripts/ci/deploy-pr-on-jenkins.sh

before_deploy:
  - docker build -t ${DOCKER_USER}/${DOCKER_REPO} .

deploy:
  - provider: script
    script: ./scripts/ci/publish-docker-image.sh
    on:
      all_branches: true
